### ISSUE TITLE
FTP does not connect with Cyberduck

### ISSUE THREAD

**Issue by Furyhunter** [henkaku/VitaShell#3]
Cyberduck (FTP client for OSX) soft hangs in a connecting state when attempting to connect to the shell to transfer files.

I don't have much more info at the moment, not at my Air to test it further.

**Comment by yifanlu** [comment]
Open an issue with https://github.com/xerpi/libftpvita

**Comment by p-sebastian** [comment]
Did anybody get a fix n this?, I get timeouts with 8.0 also on cyberduck
